/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CircleArea.h"

double *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("Area of circle with radius %d \n", argp->a);
	result=argp->a*argp->a*3.14;

	return &result;

	
}
