/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CIRCLEAREA_H_RPCGEN
#define _CIRCLEAREA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
};
typedef struct numbers numbers;

#define CircleArea_PROG 0x23451111
#define CircleArea_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  double * add_1(numbers *, CLIENT *);
extern  double * add_1_svc(numbers *, struct svc_req *);
extern int circlearea_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  double * add_1();
extern  double * add_1_svc();
extern int circlearea_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CIRCLEAREA_H_RPCGEN */
