/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CircleArea.h"


void
circlearea_prog_1(char *host,int x)
{
	CLIENT *clnt;
	double  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CircleArea_PROG, CircleArea_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a=x;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
	printf("The area of the circle is %f \n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host radius\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	circlearea_prog_1 (host,atoi(argv[2]));
exit (0);
}
